# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: jekyll-agency

url: "https://hebammenpraxis-paradieskind.de" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: Hebammenpraxis Paradieskind
email: info@hebammenpraxis-paradieskind.de #this is also the email contact forms will go to
description: Deine Hebammenpraxis in Jena
author: Hebammenpraxis Paradieskind
google_site_verification: S1ZgmUCa19ifQx4c1O6ry4N11QbEqCTcMjuNEVtALxw
webmaster_verifications:
  google: S1ZgmUCa19ifQx4c1O6ry4N11QbEqCTcMjuNEVtALxw
  bing: A6D940310C7D7F0F3591CB34A5A673E9
  alexa:
  yandex:
  baidu:
  facebook:
# logo: #optional, defaults to site title
#   path: assets\img\clients\creative-market.jpg
#   height: 60 #height in px, defaults to 52px

locale: "de-DE" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  leistungen:
  kurse:
  zusatzangebote:

markdown: kramdown
# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-imagemagick

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ["robots.txt"]
  uglifier_args:
    harmony: true

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: true # enables responsive images for your site (recommended, see https://github.com/alshedivat/al-folio/issues/537)
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
  output_formats:
    webp: "-resize 800x"
